models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from tinymce import models as tinymce_models
from django import forms
from djangoratings.fields import RatingField
from django.forms.widgets import *
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.db.models.signals import post_save
import hashlib
from datetime import *
import urllib2

class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    topic = forms.CharField()
    message = forms.CharField(widget=Textarea())

class MapStyle(models.Model):#модель для типа маркера на карте
    title = models.CharField(max_length=100)
    value = models.CharField(max_length=100)
	
    def __unicode__(self): #дополнительное поле, определяет информацию. выводимю на экран
        return self.title	

class OrdersLisrt(models.Model):
	user = models.ForeignKey(User, verbose_name='Пользователь')
	summ = models.CharField(max_length=50, verbose_name='Сумма')
	date = models.DateTimeField('Дата платежа')
	lng = models.CharField(max_length=255, verbose_name='Комментарий', null=True, blank=True)	
	def __unicode__(self): #дополнительное поле, определяет информацию. выводимю на экран
		return self.lng		
		
class tst_r(models.Model):
	rating = RatingField(range=5, allow_anonymous = True, use_cookies = True)			
		
class Firm(MPTTModel):#модель БД для фирм и организаций, наследуется от класса. поддерживающего дерево
	#далее просто указываеются все необходимые поля
	#поле "имя" - не проверяется, но должно быть уникально в пределах категории.
  name = models.CharField(max_length=50, verbose_name='Название')
	#поле "псевдоним" - не проверяется, но должно быть уникально в пределах категории.
  alias = models.CharField(max_length=50, unique=True, verbose_name='Псевдоним')	
	#указание поля, благодаря которому древовидная стукрута вообще работает
  parent = TreeForeignKey('self', null=True, blank=True, related_name='children')
	#Логическая переменная, определяющая, по сути, в каком шаблоне отображать модель
  container = models.BooleanField(verbose_name='Контейнер?', default = False)
	#короткое описание, показывается на карте и в отображении списком
  short = tinymce_models.HTMLField(verbose_name='Короткое описание', null=True, blank=True)
	#Полный текст описания фирмы
  description = tinymce_models.HTMLField(verbose_name='Полный текст', null=True, blank=True)
	#изображения, привязанные к фирме
  image1 = models.ImageField(upload_to='uploads', verbose_name='Изображение 1', null=True, blank=True)
  image2 = models.ImageField(upload_to='uploads', verbose_name='Изображение 2', null=True, blank=True)
  image3 = models.ImageField(upload_to='uploads', verbose_name='Изображение 3', null=True, blank=True)
  image4 = models.ImageField(upload_to='uploads', verbose_name='Изображение 4', null=True, blank=True)
	#ключевые слова
  meta_key = models.CharField(max_length=100, verbose_name='Ключевые слова', null=True, blank=True)
	#строка адреса фирмы
  location = models.CharField(max_length=100, verbose_name='Адрес', null=True, blank=True)
  lat = models.CharField(max_length=255, verbose_name='Широта', null=True, blank=True)
  lng = models.CharField(max_length=255, verbose_name='Долгота', null=True, blank=True)
	#стиль отображения на карте. Проще сделать отдельной таблицей все значения.
  map_style = models.ForeignKey(MapStyle, verbose_name='Стиль на карте', null=True, blank=True)
	#Логическая переменная, определяющая, является ли данный объект магазином
  isstore = models.BooleanField(verbose_name='Магазин?', default = False)
	#поле "ecwid" - необходимое поле в случае, если ресурс - магазин.
  ecwid = models.CharField(max_length=50, verbose_name='ID магазина ECWID', null=True, blank=True)
	#дата создания ресурса
  pub_date = models.DateTimeField('Дата публикации', null=True, blank=True, default = datetime.now())	
	#переменная для количества голосов
  totalvotes = models.BigIntegerField(verbose_name='Количество проголосовавших', null=True, blank=True)
	#переменная для подсчёта рейтинга
  #raiting = models.FloatField(verbose_name='Рейтинг', null=True)
  rating = RatingField(range=5, allow_anonymous = True, use_cookies = True, null=True, blank=True)
  published = models.BooleanField(verbose_name='Опубликовано?', default = False)

  class MPTTMeta:#метадата для деревьев
    order_insertion_by = ['name']
		
  def __unicode__(self): #дополнительное поле, определяет информацию. выводимю на экран
    return self.name	
		
class Event(models.Model):
	#поле "имя" - должно быть уникально.
	name = models.CharField(max_length=50, unique=True, verbose_name='Название')
	#короткое описание, показывается в отображении списком
	short = tinymce_models.HTMLField(verbose_name='Короткое описание')
	#Полный текст описания фирмы
	description = tinymce_models.HTMLField(verbose_name='Полный текст')
	#дата создания ресурса
	start_date = models.DateTimeField('Дата начала')	
	#дата создания ресурса
	end_date = models.DateTimeField('Дата окончания')
	
	def __unicode__(self): #дополнительное поле, определяет информацию. выводимю на экран
		return self.name	
		
class Article(models.Model):#модель для статьи.
	#поле "имя" - должно быть уникально.
	name = models.CharField(max_length=50, unique=True, verbose_name='Название')
	#короткое описание, показывается в отображении списком
	short = tinymce_models.HTMLField(verbose_name='Короткое описание')
	#Полный текст описания фирмы
	description = tinymce_models.HTMLField(verbose_name='Полный текст')
	#ключевые слова
	meta_key = models.CharField(max_length=100, verbose_name='Ключевые слова')
	#дата создания ресурса
	pub_date = models.DateTimeField('Дата публикации')		
	
	def __unicode__(self): #дополнительное поле, определяет информацию. выводимю на экран
		return self.name
		
class UserProfile(models.Model):
    # This field is required.
    user = models.OneToOneField(User)

    # Other fields here
    editor_for = models.ForeignKey(Firm, verbose_name='Редактирует фирму:', null=True, blank=True)
    generated_password = models.CharField(max_length=255, verbose_name='Сгенерированный пароль', null=True, blank=True)
    generated_email = models.CharField(max_length=255, verbose_name='Сгенерированный email', null=True, blank=True)
    paid_till = models.DateTimeField('Оплачено до', null=True, blank=True)	
	
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            token = "cbe688b751993340999aceaa28432eba44eeb4eb418388e309bbdcb5"
            crc  = hashlib.md5(instance.username+str(instance.id)+"someSalT").hexdigest()[:10]
            url = "https://pddimp.yandex.ru/reg_user_token.xml?token="+token+"&u_login="+instance.username+"&u_password="+crc
            result = urllib2.urlopen(url)
            
            UserProfile.objects.create(user=instance, generated_password=crc, generated_email=instance.username+"@allvbg.ru", paid_till = datetime.now())		
			
    post_save.connect(create_user_profile, sender=User)	
	
class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        exclude = ('password','editor_for','is_staff','is_active','is_superuser','last_login','date_joined','groups','user_permissions')
			
class FirmUserForm(forms.ModelForm):
    class Meta:
        model = Firm
        exclude = ('rating','raiting','totalvotes','pub_date','ecwid','isstore','map_style','meta_key','container','alias','parent')

class FirmForm(forms.ModelForm):
  class Meta:
    model = Firm
    exclude = ('ecwid', 'isstore', 'container', 'alias', 'published')

templates/bootstrap/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{%block title%} Оформление платежа {%endblock%}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{%block description%} description {%endblock%}">
    <meta name="author" content="pman">
	  <base href="http://allvbg.ru/" />
    <link href="{{ STATIC_URL }}allvbg/bootstrap.min.css" rel="stylesheet">
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="favicon.ico">	
  	<script src="{{ STATIC_URL }}allvbg/js/jquery-1.8.3.js" type="text/javascript"></script>
  	<script type="text/javascript" src="{{ STATIC_URL }}allvbg/redactor/redactor.js"></script>
    <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-alert.js" type="text/javascript"></script>
  	<link rel="stylesheet" href="{{ STATIC_URL }}allvbg/redactor/css/redactor.css" type="text/css" />
  </head>

  <body>
    {% block body %}
      <style>
        body {
          padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        }
      </style>
      <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
      		  {%block topbar%}
                <a class="brand" href="#">Весь Выборг</a>
                <div class="nav-collapse">
                  <ul class="nav">
                    <li class="active"><a href="#">Главная</a></li>
      			        <li class="active"><a href="/accounts/profile/">Профиль</a></li>
                  </ul>
                </div>
      		  {%endblock%}
          </div>
        </div>
      </div>

      <div class="container">
  		{%block content%}
  			{% if f %}
    			<form class="form-horizontal" method="post" action="/accounts/profile/edit/">  				
    				{% csrf_token %}  				
    					{% for field in f %}
    					<div class="control-group">
    						{{ field.label_tag }}
    						<div class="controls">
    							{{ field }}
    						</div>
    					</div>
    					{% endfor %}  					
    				<div class="form-actions">
    					<input type="submit" class="btn btn-primary" value="Изменить" />
    				</div>  				
    			</form>
  			{% else %}
  				<center>
  					<h4>Ошибка в параметрах платежа.</h4>
  					<br />
  					<p>Если вы уверены, что ошибка на нашей стороне - свяжитесь с <a href="mailto:admin@allvbg.ru">администратором.</a></p>
  				</center>
  			{% endif %}
  			
  			{% if dt%}
  				{{dt|date:"Y-m-d"}}
  			{% endif %}
  			
  		{%endblock%}
      </div>
    {% endblock %}
  </body>
</html>

templates/bootstrap/firm_edit.html
	<br/>
	<br/>
	<br/>
	{% if firm %}
		<form class="form-horizontal" method="post" action="/accounts/profile/firm/" enctype="multipart/form-data">
			<fieldset>
				{% csrf_token %}
				<div class="control-group">
					<label class="control-label" for="id_name">Название</label>
					<div class="controls">
						<input type="text" class="input-xlarge" id="id_name" name="name" value="{{firm.name}}">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="id_short">Описание короткое</label>
					<div class="controls">				
						<textarea class="input-xlarge" id="id_short" name="short" rows="3">{{firm.short}}</textarea>					
					</div>
				</div>	
				<div class="control-group">
					<label class="control-label" for="id_description">Полный текст</label>
					<div class="controls">					
						<textarea class="input-xlarge" id="id_description" name="description" rows="3">{{firm.description}}</textarea>					
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="id_image1">Изображение 1</label>
					<div class="controls">
						<input class="input-file" id="id_image1" name="image1" type="file">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="id_image2">Изображение 2</label>
					<div class="controls">
						<input class="input-file" id="id_image2" name="image2" type="file">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="id_image3">Изображение 3</label>
					<div class="controls">
						<input class="input-file" id="id_image3" name="image3" type="file">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="id_image4">Изображение 4</label>
					<div class="controls">
						<input class="input-file" id="id_image4" name="image4" type="file">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="id_last_name">Положение на карте</label>
					<div class="controls">
						<div>
							<input type="text" class="vTextField" id="YMapsInput">
							<input id="b1" value="Найти!" onclick="enter();" type="button"/>
							<div id="YMapsID" style="width: 620px; height: 300px;"></div>
						</div>
						<input type="hidden" class="input-xlarge" id="id_location" name="location" value="{{firm.location}}">
						<input type="hidden" class="input-xlarge" id="id_lat" name="lat" value="{{firm.lat}}">
						<input type="hidden" class="input-xlarge" id="id_lng" name="lng" value="{{firm.lng}}">
					</div>
				</div>		
				<div class="form-actions">
					<input type="submit" class="btn btn-primary" value="Изменить" />
					<input type="button" name="Отменить" class="btn" value="Отменить" onclick="window.location = '/accounts/profile/' " />
				</div>
				
			</fieldset>
		</form>
	{% else %}
		<center>
			<h4>Период редактирования фирмы закончился.</h4>
			<br />
			<p>Пожалуйста, оплатите редактиование, нажав кнопку <strong>"Оплатить"</strong>.</p>
			<p>Если вы уверены, что ошибка на нашей стороне - свяжитесь с <a href="mailto:admin@allvbg.ru">администратором.</a></p>
		</center>
	{% endif %}

templates/bootstrap/profile.html
{% extends "allvbg/bootstrap/base.html" %}
{%block title%} Профиль {%endblock%}
{%block description%} описание {%endblock%}
{%block topbar%}
	<a class="brand" href="#">Весь Выборг</a>
	<div class="nav-collapse">
		<ul class="nav">
			<li class="active"><a href="http://allvbg.ru/">Главная</a></li>
			<li class="active"><a href="/accounts/profile/">Профиль</a></li>
			<li class="active"><a href="/{{user.get_profile.editor_for.id}}" target="_blank">Фирма</a></li>
			<li class="active"><a href="/accounts/logout/">Выйти</a></li>
			<li class="brand">
				<form action="/i18n/setlang/" method="post" style="margin:0;">
					{% csrf_token %}
					<input value="" name="language" type="hidden">
					<input onclick="this.form.language.value=this.value" title="English" value="en" src="{{ STATIC_URL }}/allvbg/img/en.png" name="langpair" type="image">
					<input onclick="this.form.language.value=this.value" title="Russian" value="ru" src="{{ STATIC_URL }}/allvbg/img/ru.png" name="langpair" type="image">
				</form>
			</li>
		</ul>
	</div>
{%endblock%}
{%block content%}

<div class="row-fluid">
	<div class="span5">
		<br />
		<blockquote style="text-align:justify;">
			<p>
				Для редактирования своей фирмы на английском языке щёлкните по соответствующему флагу в верху страницы. По кнопке <strong>"Редактировать фирму"</strong> будет доступно редактирование англоязычной версии.
			</p>
			<p>
				Для возврата к русской версии данных просто щёлкните по соответствующему флагу в шапке сайта.
			</p>
			<hr />
			<p>
				Редактирование доступно только при условии оплаты за период доступа.
				Для оплаты воспользуйтесь кнопкой <strong>"Оплатить"</strong>.
			</p>
		</blockquote>	
	</div>
	<div class="span7">
		<table class="table table-striped table-bordered">
		  <tbody>
			<tr>
			  <td><b>Логин:</b></td>
			  <td>{{user}}</td>
			</tr>
			<tr>
			  <td><b>Имя:</b></td>
			  <td>{{user.first_name}}</td>
			</tr>
			<tr>
			  <td><b>Фамилия:</b></td>
			  <td>{{user.last_name}}</td>
			</tr>
			<tr>
			  <td><b>Электронная почта:</b></td>
			  <td><a href="mailto:{{user.email}}">{{user.email}}</a></td>
			</tr>
			<tr>
			  <td><b>Почта на allvbg.ru:</b></td>
			  <td><a href="mailto:{{user.get_profile.generated_email}}">{{user.get_profile.generated_email}}</a></td>
			</tr>
			<tr>
			  <td><b>Пароль для @allvbg.ru:</b></td>
			  <td>{{user.get_profile.generated_password}}</a></td>
			</tr>			
			<tr>
			  <td><b>Редактирует:</b></td>
			  <td><a href="/{{user.get_profile.editor_for.id}}" target="_blank">{{user.get_profile.editor_for}}</a></td>
			</tr>
			<tr>
			  <td><b>Оплачено до:</b></td>
			  <td>{{user.get_profile.paid_till|date:"d.m.Y"}}</td>
			</tr>				
		  </tbody>
		</table>
		
		<a class="btn" data-toggle="modal" href="#profile_edit" > Редактировать профиль </a>
		<a class="btn btn-primary" data-toggle="button" data-loading-text="Загрузка..." id="firm_edit_loader" href="/accounts/edit/firm/{{user.get_profile.editor_for.id}}"> Редактировать фирму </a>
		<a class="btn btn-success" data-toggle="modal" href="#pay" > Оплатить </a>
		
	</div>
</div>

<div class="modal" id="profile_edit" style="display:none;">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">×</a>
		<h3>Редактирование профиля</h3>
	</div>
	<div class="modal-body">
		<form class="form-horizontal" method="post" action="/accounts/profile/edit/">
			<fieldset>
				{% csrf_token %}
				<div class="control-group">
					<label class="control-label" for="id_username">Логин</label>
					<div class="controls">
						 <input type="text" class="input-xlarge" id="id_username" name="username" value="{{user}}">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="id_first_name">Имя</label>
					<div class="controls">
						<input type="text" class="input-xlarge" id="id_first_name" name="first_name" value="{{user.first_name}}">
					</div>
				</div>	
				<div class="control-group">
					<label class="control-label" for="id_last_name">Фамилия</label>
					<div class="controls">
						<input type="text" class="input-xlarge" id="id_last_name" name="last_name" value="{{user.last_name}}">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="id_email">Электронная почта</label>
					<div class="controls">
						<input type="text" class="input-xlarge" id="id_email" name="email" value="{{user.email}}">
					</div>
				</div>
				
				<div class="form-actions">
					<input type="submit" class="btn btn-primary" value="Изменить" />
					<input type="button" name="Отменить" class="btn" value="Отменить" onclick="window.location = '/accounts/profile/' " />
				</div>
				
			</fieldset>
		</form>	
	</div>
</div>

<div class="modal" id="pay" style="display:none;">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">×</a>
		<h3>Оплатить</h3>
	</div>
	<div class="modal-body">
		<form class="form-horizontal" method="post" action="/payment/pay/">
			<fieldset>
				{% csrf_token %}			
				<legend>Оплата производится через Робокассу</legend>
				<div class="control-group">
					<label class="control-label" for="OutSum">Срок оплаты</label>
					<div class="controls">
						<input type="hidden" name="desc" value="{{user.id}}">
						<select id="OutSum" name="OutSum">
							<option selected value="50">1 месяц - 50р.</option>
							<option value="90">2 месяца - 90р.</option>
							<option value="135">3 месяца - 135р.</option>
							<option value="250">6 месяцев - 250р.</option>
							<option value="450">12 месяцев - 450р.</option>
						</select>
					</div>
				</div>
				<div class="form-actions">
					<input type="submit" class="btn btn-success" value="Оплатить" />
					<input type="button" name="Отменить" class="btn" value="Отменить" onclick="window.location = '/accounts/profile/' " />
				</div>
			</fieldset>
		</form>
	</div>
</div>

<div class="span12" id="firm_edit_cont">
<!-- -->	
</div>

	
<script src="{{STATIC_URL}}allvbg/bootstrap.modal.js"></script>
<script src="{{STATIC_URL}}allvbg/bootstrap-tab.js"></script>
<script src="{{STATIC_URL}}allvbg/bootstrap-button.js"></script>
<script src="http://api-maps.yandex.ru/2.0/?load=package.full&lang=ru-RU"></script>


<script type="text/javascript">

	function map_this(){

	}

	$(document).ready(
		function()
		{
			$('#profile_edit').modal({show:false})

			$('#firm_edit_loader').click(function(){
				$(this).button('loading')
				$('#firm_edit_cont').load('/accounts/edit/firm/{{user.get_profile.editor_for.id}}', function(){
					$('#id_description').redactor();
					$('#id_short').redactor();
					

				  ymaps.ready(init);

				  function init () {
				    var tv = $('#id_location');
				    var ltt = $('#id_lat');
				    var lgg = $('#id_lng');
				    
				    var x = ltt.val();
				    var y = lgg.val();
				    if(!x) x = 28.738031;
				    if(!y) y = 60.713432;

				    map = new ymaps.Map("YMapsID", {center: [y, x], zoom: 14});
				    map.controls.add('zoomControl').add('typeSelector')

				    myPlacemark = new ymaps.Placemark(map.getCenter(), {hintContent: ''}, {draggable: true});

				    myCollection = new ymaps.GeoObjectCollection();

				    myPlacemark.events.add('dragend', function (e) {
				      drag_end(e, myPlacemark);
				    });

				    map.geoObjects.add(myPlacemark);

				    $('#b1').click(function () {
				      var search_query = $('#YMapsInput').val();
				      ymaps.geocode(search_query, {results: 1}).then(function (res) {

				        map.geoObjects.each(function(object){
				          map.geoObjects.remove(object);
				        })

				        res.geoObjects.each(function(object){
				          center = object.geometry.getCoordinates()
				          map.panTo(center);
				          tv.val([center[1], center[0]]);
				          ltt.val(center[1]);
				          lgg.val(center[0]);
				          geoPlacemark = new ymaps.Placemark(center, {hintContent: ''}, {draggable: true});
				          geoPlacemark.events.add('dragend', function (e) {
				            drag_end(e, geoPlacemark);
				          });
				        });

				        map.geoObjects.add(geoPlacemark);

				      });
				      return false;
				    });

				    var drag_end = function(e, placemark) {
				      var coordinates = placemark.geometry.getCoordinates();
				      tv.val([coordinates[1], coordinates[0]]);
				      ltt.val(coordinates[1]);
				      lgg.val(coordinates[0]);
				      e.stopPropagation();
				    };

				  }
					/*var map = -1
					var placemark = -1
					var tv = document.getElementById('id_location');
					var ltt = document.getElementById('id_lat');
					var lgg = document.getElementById('id_lng');
					
						var x = tv.value.substr(0, strpos(tv.value, ",", 0));
						var y = tv.value.substr(strpos(tv.value, ",", 0)+1, tv.value.length);
						if(!x) x = 28.738031;
						if(!y) y = 60.713432;
						map = new YMaps.Map(document.getElementById("YMapsID"));
						map.setCenter(new YMaps.GeoPoint(parseFloat(x), parseFloat(y)), 14);
						map.addControl(new YMaps.Zoom());
						placemark = new YMaps.Placemark(map.getCenter(), {draggable: true});
						map.addOverlay(placemark);
						
						YMaps.Events.observe(placemark, placemark.Events.DragEnd, function (obj) {
							tv.value = obj.getGeoPoint().getX() + ',' + obj.getGeoPoint().getY();
							ltt.value = obj.getGeoPoint().getX();
							lgg.value = obj.getGeoPoint().getY();			
						});
					
					function strpos(haystack, needle, offset){
						var i = haystack.indexOf( needle, offset );
						return i >= 0 ? i : false;
					}
					
					function enter() {
						var geocoder = new YMaps.Geocoder(document.getElementById("YMapsInput").value, {results: 1});
						YMaps.Events.observe(geocoder, geocoder.Events.Load, function (geocoder) {
							placemark.setGeoPoint(this.get(0).getGeoPoint());
							map.panTo(this.get(0).getGeoPoint());
							tv.value = this.get(0).getGeoPoint().getX() + ',' + this.get(0).getGeoPoint().getY()
							ltt.value = obj.getGeoPoint().getX();
							lgg.value = obj.getGeoPoint().getY();			
						});
					}*/

					$('#firm_edit_loader').button('reset')
					
				});
				return false;
			})
		}
	);
</script>

{%endblock%}

templates/bootstrap/profile_edit.html
{% extends "allvbg/bootstrap/base.html" %}
{%block title%} Редактировать профиль {%endblock%}
{%block description%} описание {%endblock%}
{%block topbar%}
	<a class="brand" href="#">Весь Выборг</a>
	<div class="nav-collapse">
		<ul class="nav">
			<li class="active"><a href="http://allvbg.ru/">Главная</a></li>
			<li class="active"><a href="/accounts/profile/">Профиль</a></li>
			<li class="active"><a href="/{{user.get_profile.editor_for.id}}" target="_blank">Фирма</a></li>
			<li class="active"><a href="/accounts/logout/">Выйти</a></li>
		</ul>
	</div>
{%endblock%}
{%block content%}
	<form class="form-horizontal" method="post" action="/">
		<fieldset>
			{% csrf_token %}
			<div class="control-group">
				<label class="control-label" for="id_username">Логин</label>
				<div class="controls">
					 <input type="text" class="input-xlarge" id="id_username" name="username" value="{{user}}">
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="id_first_name">Имя</label>
				<div class="controls">
					<input type="text" class="input-xlarge" id="id_first_name" name="first_name" value="{{user.first_name}}">
				</div>
			</div>	
			<div class="control-group">
				<label class="control-label" for="id_last_name">Фамилия</label>
				<div class="controls">
					<input type="text" class="input-xlarge" id="id_last_name" name="last_name" value="{{user.last_name}}">
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="id_email">Электронная почта</label>
				<div class="controls">
					<input type="text" class="input-xlarge" id="id_email" name="email" value="{{user.email}}">
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="fileInput">Изображение</label>
				<div class="controls">
					<input class="input-file" id="fileInput" type="file">
				</div>
			</div>
			
			<div class="form-actions">
				<input type="submit" class="btn btn-primary" value="Изменить" />
				<input type="button" name="Отменить" class="btn" value="Отменить" onclick="window.location = '/accounts/profile/' " />
			</div>
			
		</fieldset>
	</form>				

<!--<div class="row-fluid">
	<div class="span4">
		<div class="thumbnail">
			{% if user.get_profile.avatar %}
				<img src="{{ STATIC_URL }}allvbg/{{user.get_profile.avatar}}">
			{% else %}
				<img src="{{ STATIC_URL }}allvbg/img/transparent.png">
			{% endif %}	
		</div>	
	</div>
	<div class="span8">
		<table class="table table-striped table-bordered">
		  <tbody>
			<tr>
			  <td><b>Логин</b></td>
			  <td>{{user}}</td>
			</tr>
			<tr>
			  <td><b>Имя</b></td>
			  <td>{{user.first_name}}</td>
			</tr>
			<tr>
			  <td><b>Фамилия</b></td>
			  <td>{{user.last_name}}</td>
			</tr>
			<tr>
			  <td><b>Электронная почта</b></td>
			  <td><a href="mailto:{{user.email}}">{{user.email}}</a></td>
			</tr>
			<tr>
			  <td><b>Редактирует</b></td>
			  <td><a href="/{{user.get_profile.editor_for.id}}" target="_blank">{{user.get_profile.editor_for}}</a></td>
			</tr>			
		  </tbody>
		</table>
		
		<a class="btn" href="/accounts/edit/">Редактировать профиль</a>
		<a class="btn btn-primary" href="/accounts/edit/firm/{{user.get_profile.editor_for.id}}">Редактировать фирму</a>
		
	</div>
</div>-->

{%endblock%}