models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from tinymce import models as tinymce_models
from django import forms
from djangoratings.fields import RatingField
from django.forms.widgets import *
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.db.models.signals import post_save
import hashlib
from datetime import *
import urllib2

class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    topic = forms.CharField()
    message = forms.CharField(widget=Textarea())

class MapStyle(models.Model):#модель для типа маркера на карте
    title = models.CharField(max_length=100)
    value = models.CharField(max_length=100)
	
    def __unicode__(self): #дополнительное поле, определяет информацию. выводимю на экран
        return self.title	

class OrdersLisrt(models.Model):
	user = models.ForeignKey(User, verbose_name='Пользователь')
	summ = models.CharField(max_length=50, verbose_name='Сумма')
	date = models.DateTimeField('Дата платежа')
	lng = models.CharField(max_length=255, verbose_name='Комментарий', null=True, blank=True)	
	def __unicode__(self): #дополнительное поле, определяет информацию. выводимю на экран
		return self.lng		
		
class tst_r(models.Model):
	rating = RatingField(range=5, allow_anonymous = True, use_cookies = True)			
		
class Firm(MPTTModel):#модель БД для фирм и организаций, наследуется от класса. поддерживающего дерево
	#далее просто указываеются все необходимые поля
	#поле "имя" - не проверяется, но должно быть уникально в пределах категории.
  name = models.CharField(max_length=50, verbose_name='Название')
	#поле "псевдоним" - не проверяется, но должно быть уникально в пределах категории.
  alias = models.CharField(max_length=50, unique=True, verbose_name='Псевдоним')	
	#указание поля, благодаря которому древовидная стукрута вообще работает
  parent = TreeForeignKey('self', null=True, blank=True, related_name='children')
	#Логическая переменная, определяющая, по сути, в каком шаблоне отображать модель
  container = models.BooleanField(verbose_name='Контейнер?', default = False)
	#короткое описание, показывается на карте и в отображении списком
  short = tinymce_models.HTMLField(verbose_name='Короткое описание', null=True, blank=True)
	#Полный текст описания фирмы
  description = tinymce_models.HTMLField(verbose_name='Полный текст', null=True, blank=True)
	#изображения, привязанные к фирме
  image1 = models.ImageField(upload_to='uploads', verbose_name='Изображение 1', null=True, blank=True)
  image2 = models.ImageField(upload_to='uploads', verbose_name='Изображение 2', null=True, blank=True)
  image3 = models.ImageField(upload_to='uploads', verbose_name='Изображение 3', null=True, blank=True)
  image4 = models.ImageField(upload_to='uploads', verbose_name='Изображение 4', null=True, blank=True)
	#ключевые слова
  meta_key = models.CharField(max_length=100, verbose_name='Ключевые слова', null=True, blank=True)
	#строка адреса фирмы
  location = models.CharField(max_length=100, verbose_name='Адрес', null=True, blank=True)
  lat = models.CharField(max_length=255, verbose_name='Широта', null=True, blank=True)
  lng = models.CharField(max_length=255, verbose_name='Долгота', null=True, blank=True)
	#стиль отображения на карте. Проще сделать отдельной таблицей все значения.
  map_style = models.ForeignKey(MapStyle, verbose_name='Стиль на карте', null=True, blank=True)
	#Логическая переменная, определяющая, является ли данный объект магазином
  isstore = models.BooleanField(verbose_name='Магазин?', default = False)
	#поле "ecwid" - необходимое поле в случае, если ресурс - магазин.
  ecwid = models.CharField(max_length=50, verbose_name='ID магазина ECWID', null=True, blank=True)
	#дата создания ресурса
  pub_date = models.DateTimeField('Дата публикации', null=True, blank=True, default = datetime.now())	
	#переменная для количества голосов
  totalvotes = models.BigIntegerField(verbose_name='Количество проголосовавших', null=True, blank=True)
	#переменная для подсчёта рейтинга
  #raiting = models.FloatField(verbose_name='Рейтинг', null=True)
  rating = RatingField(range=5, allow_anonymous = True, use_cookies = True, null=True, blank=True)
  published = models.BooleanField(verbose_name='Опубликовано?', default = False)

  class MPTTMeta:#метадата для деревьев
    order_insertion_by = ['name']
		
  def __unicode__(self): #дополнительное поле, определяет информацию. выводимю на экран
    return self.name	
		
class Event(models.Model):
	#поле "имя" - должно быть уникально.
	name = models.CharField(max_length=50, unique=True, verbose_name='Название')
	#короткое описание, показывается в отображении списком
	short = tinymce_models.HTMLField(verbose_name='Короткое описание')
	#Полный текст описания фирмы
	description = tinymce_models.HTMLField(verbose_name='Полный текст')
	#дата создания ресурса
	start_date = models.DateTimeField('Дата начала')	
	#дата создания ресурса
	end_date = models.DateTimeField('Дата окончания')
	
	def __unicode__(self): #дополнительное поле, определяет информацию. выводимю на экран
		return self.name	
		
class Article(models.Model):#модель для статьи.
	#поле "имя" - должно быть уникально.
	name = models.CharField(max_length=50, unique=True, verbose_name='Название')
	#короткое описание, показывается в отображении списком
	short = tinymce_models.HTMLField(verbose_name='Короткое описание')
	#Полный текст описания фирмы
	description = tinymce_models.HTMLField(verbose_name='Полный текст')
	#ключевые слова
	meta_key = models.CharField(max_length=100, verbose_name='Ключевые слова')
	#дата создания ресурса
	pub_date = models.DateTimeField('Дата публикации')		
	
	def __unicode__(self): #дополнительное поле, определяет информацию. выводимю на экран
		return self.name
		
class UserProfile(models.Model):
    # This field is required.
    user = models.OneToOneField(User)

    # Other fields here
    editor_for = models.ForeignKey(Firm, verbose_name='Редактирует фирму:', null=True, blank=True)
    generated_password = models.CharField(max_length=255, verbose_name='Сгенерированный пароль', null=True, blank=True)
    generated_email = models.CharField(max_length=255, verbose_name='Сгенерированный email', null=True, blank=True)
    paid_till = models.DateTimeField('Оплачено до', null=True, blank=True)	
	
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            token = "cbe688b751993340999aceaa28432eba44eeb4eb418388e309bbdcb5"
            crc  = hashlib.md5(instance.username+str(instance.id)+"someSalT").hexdigest()[:10]
            url = "https://pddimp.yandex.ru/reg_user_token.xml?token="+token+"&u_login="+instance.username+"&u_password="+crc
            result = urllib2.urlopen(url)
            
            UserProfile.objects.create(user=instance, generated_password=crc, generated_email=instance.username+"@allvbg.ru", paid_till = datetime.now())		
			
    post_save.connect(create_user_profile, sender=User)	
	
class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        exclude = ('password','editor_for','is_staff','is_active','is_superuser','last_login','date_joined','groups','user_permissions')
			
class FirmUserForm(forms.ModelForm):
    class Meta:
        model = Firm
        exclude = ('rating','raiting','totalvotes','pub_date','ecwid','isstore','map_style','meta_key','container','alias','parent')

class FirmForm(forms.ModelForm):
  class Meta:
    model = Firm
    exclude = ('ecwid', 'isstore', 'container', 'alias', 'published')

templates/blank.html
{{msg|safe}}

templates/calend_ajax.html
{% load allvbg_extras %}
{% month_cal y m %}

templates/contact.html
<!DOCTYPE html>
{% load i18n %}
<html style='overflow:hidden;'>
	<head>
		<title>{% trans "Обратная связь" %}</title>

	  <base href="http://allvbg.ru/" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		
		<meta name="author" content="pman">
		
		<meta name='yandex-verification' content='6d7dc13dd2380f0f' />
		
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" type="text/javascript"></script>
		<script src="{{STATIC_URL}}allvbg/validate.js" type="text/javascript"></script>
		
	   <link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.3.0/bootstrap.min.css">

		<link rel="shortcut icon" href="favicon.ico">
	  
	</head>
	<body>

		<style type="text/css">
			form div.clearfix span.help-inline, form div.clearfix span.help-block {
			    color: #9D261D !important;
			}
			form {
			    background-image: url('{{ STATIC_URL }}/allvbg/img/letter.png');
			    background-repeat:no-repeat;
			    background-position:right bottom;
			}
			.actions{
			    background: none;
			    border:none;
			}
		</style>

		<script>
		  $(document).ready(function(){
		    $("#commentForm").validate();
		  });
		</script>

		<br>
		<br>
		 
		<form action="/contact/" method="post" class="form" id="commentForm">
			<fieldset>
				<legend>{% trans "Обратная связь" %}</legend>
				<input type="hidden" name="nospam:blank" value="" />
				{% csrf_token %}

				<div class="clearfix"> 
					<label for="name">
						{% trans "Имя*" %}:
					</label>
					<div class="input">
						<input class="xlarge required" type="text" size="30" type="text" name="name" minlength="2" id="name" value="" />
					</div>
				</div>
				
				<div class="clearfix">
					<label for="email">
						{% trans "Email*" %}:
					</label>
					<div class="input">
						<input class="xlarge required email" type="text" name="email" id="email" value="" />
					</div>	
				</div>
				<div class="clearfix">
					<label for="topic">
						{% trans "Тема*" %}:
					</label>
					<div class="input">
						<input class="xlarge required" type="text" name="topic" id="topic" minlength="2" value="" />
					</div>
				</div>
				
				<div class="clearfix">
					<label for="message">
						{% trans "Сообщение*" %}:
					</label>
					<div class="input">
						<textarea class="xlarge" name="message" id="message" cols="55" rows="7" value=""></textarea>			
					</div>
				</div>
			 
				<div class="actions">
					<input class="btn primary" type="submit" value="{% trans "Отправить" %}"/>
					<button class="btn" type="reset" onClick="window.parent.document.getElementById('contact_form').parentNode.removeChild(window.parent.document.getElementById('contact_form'))">{% trans "Отменить"%}</button>
				</div>
			</fieldset>
		</form>
	</body>
</html>

templates/contact_send.html
<!DOCTYPE html>
{% load i18n %}
<html>
	<head>

		<title>{% trans "Сообщение отправлено"%}</title>

	  <base href="http://allvbg.ru/" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		
		<meta name="author" content="pman">
		
		<meta name='yandex-verification' content='6d7dc13dd2380f0f' />
		
	  <link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.3.0/bootstrap.min.css">

		<link rel="shortcut icon" href="favicon.ico">
	  

	</head>
	<body>
		<br>
		<br>
		<center>
			<h2>{% trans "Ваше сообщение отправлено."%}</h2>  
			<br>
			<a class="btn large primary" href="#" onClick="window.parent.document.getElementById('contact_form').parentNode.removeChild(window.parent.document.getElementById('contact_form'))">{% trans "Закрыть"%}</a>
		</center>
	</body>
</html>

templates/firm_ajax.html
{% load allvbg_extras %}
{% load thumbnail %}
{% load ratings %}
{% load i18n %}

{% for firm in firms.object_list %}
	<div class="list_element">
		<a href="/{{firm.id}}"><h3>{{firm.name}}</h3></a>
		<img src="{% thumbnail firm.image1 120x0 %}" width="120px">
		{% do_rating_by_object request on firm.rating as vote %}
		<div class="rateit" data-pageid="{{firm.id}}" data-rateit-value="{{vote}}" data-rateit-resetable="false">
		</div>
		<hr>
		<p>{{firm.short|safe}}</p>
	</div>
{% endfor %}

<div id="pager">
	<center>
		<ul>
			{% if pagecode %}
				{% if firms.has_previous %}
					<li class="control page_switch"><a class="page_switch" href="/ajax_list/?pagecode={{pagecode}}&page={{ firms.previous_page_number }}&limit={{lmt}}">{% trans "Предыдущие" %}</a><li>
				{% endif %}

				{% for i in firms|pagination %}
					{% ifequal i "." %}		
						<li>...</li>
					{% else %}
						{% if i = firms.number %}
							<li><a class="active_page page_switch" href="/ajax_list/?pagecode={{pagecode}}&page={{i}}&limit={{lmt}}">{{i}}</a></li>
						{% else %}
							<li><a class="page_switch" href="/ajax_list/?pagecode={{pagecode}}&page={{i}}&limit={{lmt}}">{{i}}</a></li>
						{% endif %}
					{% endifequal %}
				{% endfor %}		

				{% if firms.has_next %}
					<li class="control page_switch"><a class="page_switch" href="/ajax_list/?pagecode={{pagecode}}&page={{firms.next_page_number }}&limit={{lmt}}">{% trans "Следующие" %}</a></li>
				{% endif %}
			{% else %}
				{% if firms.has_previous %}
					<li class="control page_switch"><a class="page_switch" href="/ajax_list/?page={{ firms.previous_page_number }}&limit={{lmt}}">{% trans "Предыдущие" %}</a><li>
				{% endif %}

				{% for i in firms|pagination %}
					{% ifequal i "." %}		
						<li>...</li>
					{% else %}				
						{% if i = firms.number %}
							<li><a class="active_page page_switch" href="/ajax_list/?page={{i}}&limit={{lmt}}">{{i}}</a></li>
						{% else %}
							<li><a class="page_switch" href="/ajax_list/?page={{i}}&limit={{lmt}}">{{i}}</a></li>
						{% endif %}
					{% endifequal %}
				{% endfor %}		

				{% if firms.has_next %}
					<li class="control page_switch"><a class="page_switch" href="/ajax_list/?page={{firms.next_page_number }}&limit={{lmt}}">{% trans "Следующие" %}</a></li>
				{% endif %}
			
			{% endif %}
			<div class="clear">
		</ul>
	</center>
</div>

templates/firm_form.html
<!DOCTYPE html>
<html>
  <head>
    {% load cache %}
    {% load i18n %}
    <title>{% trans "Добавить организацию"%}</title>
    <base href="http://allvbg.ru/" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    
    <script src="{{ STATIC_URL }}allvbg/js/jquery-1.8.3.js" type="text/javascript"></script>
    <script src="http://api-maps.yandex.ru/2.0/?load=package.full&lang=ru-RU" type="text/javascript"></script>

    <link rel="stylesheet" href="/static/allvbg/redactor/css/redactor.css" type="text/css" />
    <link rel="stylesheet" href="/static/allvbg/css/select2.css" type="text/css" />
    <link href="/static/allvbg/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/allvbg/css/firm/add/base.css" rel="stylesheet">

  </head>
  <body>

    <div class="container-fluid">
      <div class="row">
        <div class"span9">
          <!-- {% for key, value in form.errors.items %}
            {{key}} - {{value}}<br>
          {% endfor %} -->
          <form action="http://allvbg.ru/firm/add/" method="post" class="form-horizontal"  enctype="multipart/form-data">          
            <fieldset>
              <input id="id_totalvotes" maxlength="50" name="totalvotes" type="hidden" value="0" />
              <input id="id_raiting" maxlength="50" name="raiting" type="hidden" value="0" />
              <legend>{% trans "Добавить организацию"%}</legend>
              {% csrf_token %}
                <div class="control-group">
                  <label class="control-label">{{ form.name.label_tag }}</label>
                  <div class="controls">
                    <input class="input-block-level" id="id_name" maxlength="100" name="name" type="text" />
                  </div>
                </div>

                <div class="control-group">
                  <label class="control-label">Категория</label>
                  <div class="controls">
                    <input type="hidden" id="id_parent" name="parent" />
                  </div>
                </div>

                <div class="control-group">
                  <label class="control-label">{{ form.short.label_tag }}</label>
                  <div class="controls">
                    <textarea class="input-block-level" cols="40" id="id_short" name="short" rows="10"></textarea>
                  </div>
                </div>

                <div class="control-group">
                  <label class="control-label">{{ form.description.label_tag }}</label>
                  <div class="controls">
                    <textarea class="input-block-level" cols="40" id="id_description" name="description" rows="10"></textarea>
                  </div>
                </div>

                <div class="control-group">
                  <label class="control-label">{{ form.image1.label_tag }}</label>
                  <div class="controls">
                    {{ form.image1 }}
                  </div>
                </div>

                <div class="control-group">
                  <label class="control-label">{{ form.image2.label_tag }}</label>
                  <div class="controls">
                    {{ form.image2 }}
                  </div>
                </div>

                <div class="control-group">
                  <label class="control-label">{{ form.image3.label_tag }}</label>
                  <div class="controls">
                    {{ form.image3 }}
                  </div>
                </div>

                <div class="control-group">
                  <label class="control-label">{{ form.image4.label_tag }}</label>
                  <div class="controls">
                    {{ form.image4 }}
                  </div>
                </div>

                <div class="control-group">
                  <label class="control-label">{{ form.meta_key.label_tag }}</label>
                  <div class="controls">
                    <input class="input-block-level" id="id_meta_key" maxlength="100" name="meta_key" type="text" />
                  </div>
                </div>

                <div class="control-group">
                  <label class="control-label">{{ form.location.label_tag }}</label>
                  <div class="controls">
                    <div>
                      <input type="text" class="vTextField" id="YMapsInput"/>
                      <input id="b1" value="Найти!" type="button"/>
                      <div id="YMapsID" style="width: 620px; height: 300px;"></div>
                    </div>
                    <input type="hidden" class="input-xlarge" id="id_location" name="location" >
                    <input type="hidden" class="input-xlarge" id="id_lat" name="lat" >
                    <input type="hidden" class="input-xlarge" id="id_lng" name="lng" >
                  </div>
                </div>

                <div class="form-actions">
                  <input type="submit" class="btn btn-primary" value="Добавить" />
<!--                   <input type="button" name="Отменить" class="btn" value="Отменить" onclick="window.location = '/firm/add/' " /> -->
                </div>

             </fieldset>
          </form>
        </div>   
      </div>
    </div>


    <script type="text/javascript" src="/static/allvbg/redactor/redactor.js"></script>
    <script type="text/javascript" src="/static/allvbg/js/flow.js"></script>
    <script type="text/javascript" src="/static/allvbg/js/select2.js"></script>
    <script type="text/javascript" src="/static/allvbg/js/firm/add/base.js"></script>

  </body>
</html>

templates/google.html
google-site-verification: googlec7fb9df20f08fcee.html

templates/login.html
{% extends "allvbg/bootstrap/base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %}
	{% trans "Авторизация" %}
{% endblock %}
		

{% block body %}
	<style type="text/css">
		html {
			height: 100%;
		}
		body {
			height: 100%;
			/*background: #3d3d3d;*/
		}
		.backround_blured{
			position: absolute;
			top:0px;
			left:0px;
			z-index: 1;
			height: 100%;
			overflow: hidden;
		}
		.backround_blured img{
			width: 100%;
		}
		.form-actions {
			background: none;
			border-top: none;
		}
		form div.clearfix span.help-inline, form div.clearfix span.help-block {
		    color: #9D261D !important;
		}
		.login_form{
			background: #fff;
			-webkit-border-radius: 5px;
				 -moz-border-radius: 5px;
							border-radius: 5px;
		}
		h3{
			margin-top: 20px;
		}
		input{
			width: 90%;
		}
		.container-fluid{
			z-index: 2;
			position: relative;
		}
	</style>
	<!--<link rel="stylesheet" href="{{STATIC_URL}}allvbg/bootstrap.min.css">-->
	<script>
	   $(".alert").alert()
	</script>
	<div class="backround_blured">
		<img src="{{ STATIC_URL }}allvbg/images/login_bg.jpg" />
	</div>
	<div class="container-fluid">
		<div class="row-fluid" style="margin-top:200px;">
			<div class="span4">&nbsp;</div>
			<div class="span4 login_form">
				
				{% if form.errors %}
				<div class="span4 alert alert-block alert-error fade in">
					<a class="close" data-dismiss="alert" href="#">&times;</a>
					<h4 class="alert-heading">{% trans "Ошибка!"%}</h4>
					<p>{% trans "Неправильный логин или пароль. Попробуйте ещё раз."%}</p>
				</div>
				{% endif %}

				<h3><center>Авторизация</center><br /></h3>
				
				<form class="form-horizontal" method="post" action="{% url 'django.contrib.auth.views.login' %}">
					<fieldset>
						{% csrf_token %}
						<div class="control-group">
							<label class="control-label" for="id_username">{{ form.username.label }}</label>
							<div class="controls">
								{{ form.username }}
							</div>
						</div>					
						<div class="control-group">
							<label class="control-label" for="id_username">{{ form.password.label }}</label>
							<div class="controls">
								{{ form.password }}
							</div>
						</div>
						<div class="form-actions">
							<input type="submit" class="btn btn-primary" value="{% trans "Войти" %}" />
							<a class="btn" href="/register">{% trans "Регистрация"%}</a>
							<input type="hidden" name="next" value="{{ next }}" />
						</div>
					</fieldset>
				</form>			
				
			</div>
		</div>
	</div>
{% endblock %}

templates/message.html
<li class="rssBody"><h3>{{article.name}}</h3><br>{{article.short|safe}}</li>

templates/month_cal.html
<script type='text/javascript'>
$(document).ready(function(){
	$('#Calendar .prev a, #Calendar .next a').live('click',function(){
		$('#Calendar .calendar').css('opacity','0.3');
		date=$(this).data('rel');
		//d_m=date.split(' ')[1];
		//d_m=date.split(' ')[0];
		$.get('calend_ajax/',{action:'refreshCalendar',/*d_m:d_m,d_y:d_y*/date:date},function(data){
			$('#Calendar').html(data);
			$('#Calendar .calendar').css('opacity','1');
		})
		return false;
	})
	$('#Calendar .isevent').live('mouseenter',function(){
		id=this.id;
		$('#'+id+' .event').show();
	})
	$('#Calendar .isevent').live('mouseleave',function(){
		id=this.id;
		$('#'+id+' .event').hide();
	})
});
</script>


    <table class='calendar'>
		<tr>
			<td class='prev'><a href='#' data-rel='{{extra.prev_date}}'>&laquo;</a></td>
			<td class='month' colspan='5'>{{extra.date|date:"F Y"}} {{extra.year}}</td>
			<td class='next'><a href='#' data-rel='{{extra.next_date}}'>&raquo;</a></td>
        </tr>
		<tr>
			{% for day in headers %}
				<th class='dow'>{{ day|date:"D"|slice:":2" }}</th>
			{% endfor %}
		</tr>
			{% for week in calendar %}
				<tr>
					{% for day in week %}
						{% if day.in_month %}
							<td class="{% if day.weekend%}weekend{% else %}workday{% endif %}{% if day.isevent %} isevent {% else %} noevent {% endif %}" id="{{day.day|date:"dmY"}}">
								<div class='date'>{{ day.day|date:"j" }}</div>
								<div class='event' style="display:none;">
									{% if day.isevent %}
										<div>
											{% for event in day.events %}
												<div class="num">
													<span class="eventdate">{{event.start_date|date:"d-m-Y"}}</span>
												</div>
												<span class="link">
													<a href="/events/{{event.id}}" target = "_blank">{{event.name}}</a>
												</span>
												<br>
												<span class="notice">
													<small>{{event.short|safe}}</small>
												</span>
											{% endfor %}
										</div>
									{% endif %}								
								</div>							
							</td>
						{% else %}
							<td class="emptyday">
							</td>							
						{% endif %}
					{% endfor %}
				</tr>
			{% endfor %}
	</table>

templates/pagination.html
<div id="pager">
{% if pagecode %}
	{% ifnotequal pages 1 %}
		{% if lower_page %} 
			<li class="control page_switch"><a class="page_switch" href="/ajax_list/?page={{ lower_page }}&pagecode={{pagecode}}&limit={{limit}}">&laquo;&laquo;</a></li>
		{% endif %}
		{% for number in page_list %}
			{% ifequal number "." %}		
				<li>...</li>
			{% else %}
				{% ifequal number page %}
					<li><a class="active page_switch" href="/ajax_list/?pagecode={{pagecode}}&page={{number}}&limit={{limit}}">{{ number }}</a></li>
				{% endifequal %}
				{% ifnotequal number page %}
					<li><a class="page_switch" href="/ajax_list/?page={{ number }}&pagecode={{pagecode}}&limit={{limit}}">{{ number }}</a></li>
				{% endifnotequal %}
			{% endifequal %}
		{% endfor %}
		{% if higher_page %} 
			<li class="control page_switch"><a class="page_switch" href="/ajax_list/?page={{ higher_page }}&pagecode={{pagecode}}&limit={{limit}}">&raquo;&raquo;</a></li>
		{% endif %}
	{% endifnotequal %}
{% else %}
	{% ifnotequal pages 1 %}
		{% if lower_page %} 
			<li class="control page_switch"><a class="page_switch" href="/ajax_list/?page={{ lower_page }}&limit={{limit}}">&laquo;&laquo;</a></li>
		{% endif %}
		{% for number in page_list %}
			{% ifequal number "." %}		
				<li><a class="page_switch" href="#">...</a></li>
			{% else %}
				{% ifequal number page %}
					<li><a class="active page_switch" href="/ajax_list/?page={{number}}&limit={{limit}}">{{ number }}</a></li>
				{% endifequal %}
				{% ifnotequal number page %}
					<li><a class="page_switch" href="/ajax_list/?page={{ number }}&limit={{limit}}">{{ number }}</a></li>
				{% endifnotequal %}
			{% endifequal %}
		{% endfor %}
		{% if higher_page %} 
			<li class="control page_switch"><a class="page_switch" href="/ajax_list/?page={{ higher_page }}&limit={{limit}}">&raquo;&raquo;</a></li>
		{% endif %}
	{% endifnotequal %}
{% endif %}
</div>

templates/rss_block.html
{% for post in posts %}
	<li class="rssBody">
		<a href={{post.link}}>{{post.title}}</a><br>{{post.date|date:"d-m-Y"}}
	</li>
{% endfor %}